// Random search terms — mix of natural-looking queries
const QUERIES = [
  'best coffee shops near me',
  'weather forecast this week',
  'how to make pasta from scratch',
  'latest tech news today',
  'healthy breakfast recipes',
  'best budget smartphones 2026',
  'how does solar energy work',
  'top rated movies this year',
  'easy home workout routines',
  'best hiking trails australia',
  'how to grow tomatoes',
  'world news headlines',
  'best noise cancelling headphones',
  'simple dinner ideas',
  'how to fix a leaky tap',
  'best books to read 2026',
  'beginner guitar chords',
  'cheap flights to bali',
  'how to clean an oven naturally',
  'best free vpn services',
  'history of the internet',
  'how to tie a tie',
  'best board games for adults',
  'sydney events this weekend',
  'meal prep ideas for beginners',
  'how to improve wifi signal',
  'best electric cars australia',
  'diy home improvement projects',
  'how to make sourdough bread',
  'best podcast recommendations',
  'tips for better sleep',
  'how to save money on groceries',
  'best running shoes 2026',
  'indoor plant care tips',
  'quick lunch recipes',
  'best australian beaches',
  'how to start a side hustle',
  'beginner yoga poses',
  'how to remove stains from clothes',
  'best documentaries on netflix',
  'how to sharpen kitchen knives',
  'australian housing market 2026',
  'best wireless earbuds under 100',
  'how to compost at home',
  'easy cocktail recipes',
  'best standing desks',
  'how to train for a marathon',
  'weekend getaway ideas',
  'best air fryer recipes',
  'how to negotiate a raise',
  'top programming languages 2026',
  'best national parks australia',
  'how to fix scratched glasses',
  'meal ideas with chicken',
  'best bluetooth speakers',
  'how to start meditating',
  'simple cake recipes',
  'best budget laptops 2026',
  'how to remove rust',
  'gardening tips for beginners',
]

export function getRandomQueries(count) {
  const shuffled = [...QUERIES].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
